/*
 * Decision Service Fleet Manager
 *
 * Decision Service Fleet Manager is a Rest API to manage decision instances and connectors.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package decisclient

import (
	"encoding/json"
)

// DecisionRequestAllOfEventingKafka struct for DecisionRequestAllOfEventingKafka
type DecisionRequestAllOfEventingKafka struct {
	Source *string `json:"source,omitempty"`
	Sink   *string `json:"sink,omitempty"`
}

// NewDecisionRequestAllOfEventingKafka instantiates a new DecisionRequestAllOfEventingKafka object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecisionRequestAllOfEventingKafka() *DecisionRequestAllOfEventingKafka {
	this := DecisionRequestAllOfEventingKafka{}
	return &this
}

// NewDecisionRequestAllOfEventingKafkaWithDefaults instantiates a new DecisionRequestAllOfEventingKafka object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecisionRequestAllOfEventingKafkaWithDefaults() *DecisionRequestAllOfEventingKafka {
	this := DecisionRequestAllOfEventingKafka{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *DecisionRequestAllOfEventingKafka) GetSource() string {
	if o == nil || o.Source == nil {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionRequestAllOfEventingKafka) GetSourceOk() (*string, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *DecisionRequestAllOfEventingKafka) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *DecisionRequestAllOfEventingKafka) SetSource(v string) {
	o.Source = &v
}

// GetSink returns the Sink field value if set, zero value otherwise.
func (o *DecisionRequestAllOfEventingKafka) GetSink() string {
	if o == nil || o.Sink == nil {
		var ret string
		return ret
	}
	return *o.Sink
}

// GetSinkOk returns a tuple with the Sink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionRequestAllOfEventingKafka) GetSinkOk() (*string, bool) {
	if o == nil || o.Sink == nil {
		return nil, false
	}
	return o.Sink, true
}

// HasSink returns a boolean if a field has been set.
func (o *DecisionRequestAllOfEventingKafka) HasSink() bool {
	if o != nil && o.Sink != nil {
		return true
	}

	return false
}

// SetSink gets a reference to the given string and assigns it to the Sink field.
func (o *DecisionRequestAllOfEventingKafka) SetSink(v string) {
	o.Sink = &v
}

func (o DecisionRequestAllOfEventingKafka) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Source != nil {
		toSerialize["source"] = o.Source
	}
	if o.Sink != nil {
		toSerialize["sink"] = o.Sink
	}
	return json.Marshal(toSerialize)
}

type NullableDecisionRequestAllOfEventingKafka struct {
	value *DecisionRequestAllOfEventingKafka
	isSet bool
}

func (v NullableDecisionRequestAllOfEventingKafka) Get() *DecisionRequestAllOfEventingKafka {
	return v.value
}

func (v *NullableDecisionRequestAllOfEventingKafka) Set(val *DecisionRequestAllOfEventingKafka) {
	v.value = val
	v.isSet = true
}

func (v NullableDecisionRequestAllOfEventingKafka) IsSet() bool {
	return v.isSet
}

func (v *NullableDecisionRequestAllOfEventingKafka) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecisionRequestAllOfEventingKafka(val *DecisionRequestAllOfEventingKafka) *NullableDecisionRequestAllOfEventingKafka {
	return &NullableDecisionRequestAllOfEventingKafka{value: val, isSet: true}
}

func (v NullableDecisionRequestAllOfEventingKafka) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecisionRequestAllOfEventingKafka) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
