/*
 * Decision Service Fleet Manager
 *
 * Decision Service Fleet Manager is a Rest API to manage decision instances and connectors.
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package decisclient

import (
	"encoding/json"
)

// ServiceStatus Schema for the service status response body
type ServiceStatus struct {
	Decisions *ServiceStatusDecisions `json:"decisions,omitempty"`
}

// NewServiceStatus instantiates a new ServiceStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceStatus() *ServiceStatus {
	this := ServiceStatus{}
	return &this
}

// NewServiceStatusWithDefaults instantiates a new ServiceStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceStatusWithDefaults() *ServiceStatus {
	this := ServiceStatus{}
	return &this
}

// GetDecisions returns the Decisions field value if set, zero value otherwise.
func (o *ServiceStatus) GetDecisions() ServiceStatusDecisions {
	if o == nil || o.Decisions == nil {
		var ret ServiceStatusDecisions
		return ret
	}
	return *o.Decisions
}

// GetDecisionsOk returns a tuple with the Decisions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceStatus) GetDecisionsOk() (*ServiceStatusDecisions, bool) {
	if o == nil || o.Decisions == nil {
		return nil, false
	}
	return o.Decisions, true
}

// HasDecisions returns a boolean if a field has been set.
func (o *ServiceStatus) HasDecisions() bool {
	if o != nil && o.Decisions != nil {
		return true
	}

	return false
}

// SetDecisions gets a reference to the given ServiceStatusDecisions and assigns it to the Decisions field.
func (o *ServiceStatus) SetDecisions(v ServiceStatusDecisions) {
	o.Decisions = &v
}

func (o ServiceStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Decisions != nil {
		toSerialize["decisions"] = o.Decisions
	}
	return json.Marshal(toSerialize)
}

type NullableServiceStatus struct {
	value *ServiceStatus
	isSet bool
}

func (v NullableServiceStatus) Get() *ServiceStatus {
	return v.value
}

func (v *NullableServiceStatus) Set(val *ServiceStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceStatus(val *ServiceStatus) *NullableServiceStatus {
	return &NullableServiceStatus{value: val, isSet: true}
}

func (v NullableServiceStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
