== rhoas decision list

ifdef::env-github,env-browser[:relfilesuffix: .adoc]

List all Decision instances

=== Synopsis

List all Decision instances.

This command will provide a high level view of all Decision instances.
The fields displayed are: ID, Name, Version, Status.
Use the describe command to view all fields for a specific instance.

The instances are displayed by default in a table, but can also be displayed as JSON or YAML.


....
rhoas decision list [flags]
....

=== Options

....
      --limit int       The maximum number of Decision instances to be returned (default 100)
  -o, --output string   Format in which to display the Decision instances. Choose from: "json", "yml", "yaml"
      --page int        Display the Decision instances from the specified page number.
      --search string   Text search to filter the Decision instances by name, version and status
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas_decision{relfilesuffix}[rhoas decision]	 - Create, view, use, and manage your Decision instances

