== rhoas decision describe

ifdef::env-github,env-browser[:relfilesuffix: .adoc]

View configuration details of an Decision instance

=== Synopsis

View configuration fields and their values for an Decision instance.

Pass the "--id" flag to specify which instance you would like to view.

If the "--id" flag is not passed then the selected Decision instance will be used, if available.

You can view the output as either as JSON or YAML.


....
rhoas decision describe [flags]
....

=== Examples

....
# view the current Decision instance instance
$ rhoas decision describe

# view a specific instance by passing the --id flag
$ rhoas decision describe --id=1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

# customise the output format
$ rhoas decision describe -o yaml

....

=== Options

....
      --id string       Unique ID of the Decision instance you want to view. If not set, the current Decision instance will be used.
  -o, --output string   Format in which to display the Decision instance. Choose from: "json", "yml", "yaml" (default "json")
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas_decision{relfilesuffix}[rhoas decision]	 - Create, view, use, and manage your Decision instances

